# Generated by Django 5.0 on 2023-12-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.FileField(blank=True, null=True, upload_to='uploads/metadata/')),
                ('xml', models.FileField(blank=True, null=True, upload_to='uploads/xml/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_images', to='example.entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(related_name='entity_images', to='example.image'),
        ),
    ]
