# Generated by Django 5.0 on 2023-12-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='entity_images', to='example.image'),
        ),
    ]
