# Generated by Django 5.0 on 2023-12-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_entity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='related_entities', to='example.image'),
        ),
    ]
