# Generated by Django 5.0 on 2023-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_entity_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.CharField(choices=[('letter', 'Letter'), ('poem', 'Poem'), ('drawing', 'Drawing')], default='Letter', max_length=20),
        ),
    ]
