# Generated by Django 5.0 on 2023-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_entity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_path',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
