# Generated by Django 5.0 on 2023-12-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_alter_image_image_path_alter_image_thumbnail_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='entity',
        ),
        migrations.AlterField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, to='example.image'),
        ),
    ]
