# Generated by Django 5.0 on 2023-12-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_remove_image_entity_alter_entity_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='example.entity'),
        ),
    ]
