# Generated by Django 5.0 on 2023-12-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_remove_entity_images_image_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='entity',
        ),
        migrations.AddField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, to='example.image'),
        ),
    ]
